### ISSUE TITLE
As a project owner, I want to edit my projects

### ISSUE THREAD

**Issue by Widdershin** [Railsn00bs/the-wall#2]
As a project owner, I want to be able to edit all the detail of my projects.

We should probably make sure people can only edit projects they own.

**Comment by karencfv** [comment]
Hey @Widdershin ! I'd like to contribute to this... can we organize a day of pair programming?

**Comment by Widdershin** [comment]
Hey @karencfv, my schedule is full up until Railsn00bs, can we work on it/find a time then?

**Comment by karencfv** [comment]
@Widdershin no prob ;) thnx!!!
