### ISSUE TITLE
Replace Devise authentication with Github signup

### ISSUE THREAD

**Issue by Widdershin** [Railsn00bs/the-wall#4]
As a user, I want to authenticate with Github in order to add my projects. This also opens up the door to directly integrating with Github.

**Comment by shadrx** [comment]
@Widdershin Like I said on Saturday, I'd be keen to help with this one. 

I took a brief look for a few options we could take:
- Devise is composed of modules, among them is one called Omniauthable that provides support for another library called [Omniauth](https://github.com/intridea/omniauth-github) which is a "Standardized Multi-Provider Authentication". Long story short it has support for authenticating with many providers including [Github](https://github.com/intridea/omniauth-github). 
- We could possibly use [Omniauth](http://intridea.github.io/omniauth/) just by itself, I feel like this might mean having to deal with what devise already provides us with - error handling, model generation etc. 
- There's a [ruby wrapper ](https://github.com/intridea/oauth2) for OAuth2 - what Github uses for 3rd party auth. 

There will probably be more options too - the list above is just the result of a quick bit of procrastination while studying :p

**Comment by Widdershin** [comment]
You can now only sign in with Github :)

!!!
