### ISSUE TITLE
As a user, I want to see my own profile, so I can navigate to projects I have made

### ISSUE THREAD

**Issue by Widdershin** [Railsn00bs/the-wall#5]

**Comment by lena-pl** [comment]
- [x] Add a link to go to my profile page to the top of the wall
- [x] Create a separate page for the profile
- [x] Display a list of my projects on the profile page
- [x] Link the project descriptions on the profile page to the individual page
- [x] Create individual project pages

**Comment by Widdershin** [comment]
Closed by 4e9f66671, well done!
